# Generated by Django 4.1.1 on 2022-09-19 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_products_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('name',)},
        ),
    ]
